accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import CustomLoginForm

app_name = 'accounts'

urlpatterns = [   
    path('login/', auth_views.LoginView.as_view(authentication_form=CustomLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

loan_approval_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictions.urls')),
    path('accounts/', include('accounts.urls')),
]

predictions/urls.py
from django.urls import path
from . import views


app_name = 'predictions'

urlpatterns = [   
    path('', views.home, name='home'),
    path('apply', views.apply, name='apply'),
    path('applications', views.applications, name='applications'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].widget.attrs.update(
      {'class': 'form-control',
        'placeholder': 'Username *',
        'id': 'search-input01'
       }
    )
    
    
    self.fields['password'].widget.attrs.update(
      {'class': 'form-control', 'placeholder': 'Password *', 'id': 'search-input01'}
    )


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username *',
            'name': 'usernameeee'
        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'name': 'first_name',
            'placeholder': 'First Name *',
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'name': 'last_name',
            'placeholder': 'Last Name *',
        }
    ))
    
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'name': 'password',
            'minlength': "8",
            'placeholder': 'Password *',
        }
    ))

    password2 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'name': 'password',
            'minlength': "8",
            'placeholder': 'Confirm Password *',
        }
    ))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords dont match')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            return redirect('predictions:home')

    else:
        form = UserRegistrationForm()

    context = {
        'form': form,
    }

    return render(request, 'registration/register.html', context)

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demo.webtend.net/html/payonta/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 03 Jun 2023 22:25:01 GMT -->

<head>
    <title>LOAN APPROVAL PREDICTION SYSTEM</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include All CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/payloan-icon.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/icofont.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/preset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" />
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
</head>

<body>

    <!-- Header section -->
    <header class="header_1" id="header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-3">
                    <div class="logo">
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <nav class="mainmenu MenuInRight text-right">
                        <a href="javascript:void(0);" class="mobilemenu d-md-none d-lg-none d-xl-none">
                            <span></span>
                            <span></span>
                            <span></span>
                        </a>
                        <ul>
                            
                            
                            <li><a href="{% url 'predictions:home' %}">Home</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'predictions:applications' %}">Applications</a></li>
                                <li><a href="{% url 'accounts:logout' %}">Sign Out</a></li>
                            {% endif %}
                            
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-2 col-md-2 hidden-xs">
                    <div class="navigator_btn btn_bg text-right">
                        <a class="common_btn" href="{% url 'predictions:apply' %}">Apply Now</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header section -->
    <!-- Payloan_header_bg section -->
    {% include 'messages.html' %}
    {% block content %}
    {% endblock %}

    <!-- Include All JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <script src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/shuffle.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/gmaps.js' %}"></script>
    <script src="https://maps.google.com/maps/api/js?key=AIzaSyCysDHE3s4Qw3nTh9o58-2mJcqvR6HV8Kk"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>

<!-- Mirrored from demo.webtend.net/html/payonta/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 03 Jun 2023 22:25:20 GMT -->

</html>

accounts/templates/messages.html
{% for message in messages %}
    <div>
    <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible alert-solid" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        {{ message }}
        </div>
    </div>
        
    </div>
{% endfor %}